services:
  fastapi_app:
    build:
      context: ./fastapi_app.tf
      args:
        INTERNAL_FASTAPI_PORT: ${INTERNAL_FASTAPI_PORT}  # Pass from .env
    container_name: fastapi_app.tf
    depends_on:
      postgres:
        condition: service_healthy
      ml_model:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      ML_MODEL_URL: http://ml_model:${INTERNAL_ML_PORT}  # Use INTERNAL_PORT for ML communication
    ports:
      - "${FASTAPI_PORT}:${INTERNAL_FASTAPI_PORT}"  # Map host to container INTERNAL_PORT

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Loaded from the .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Loaded from the .env file
      POSTGRES_DB: ${POSTGRES_DB}  # Loaded from the .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume
      - ./postgres/init:/docker-entrypoint-initdb.d/  # Initialization scripts
    ports:
      - "${POSTGRES_PORT}:${INTERNAL_POSTGRES_PORT}"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  ml_model:
    build:
      context: ./ml_model
      args:
        INTERNAL_ML_PORT: ${INTERNAL_ML_PORT}  # Pass from .env
    container_name: ml_model
    ports:
      - "${ML_PORT}:${INTERNAL_ML_PORT}"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${INTERNAL_ML_PORT}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  postgres_data:
